services:
  mihomo:
    image: metacubex/mihomo:latest
    container_name: mihomo
    restart: always
    network_mode: "host" # 必须：共享宿主机网络
    cap_add:
      - NET_ADMIN        # 必须：赋予修改路由权限
    devices:
      - /dev/net/tun     # 必须：映射 TUN 设备
    volumes:
      - ./config.yaml:/root/.config/mihomo/config.yaml
      # 挂载时区，确保日志时间准确
      - /etc/localtime:/etc/localtime:ro
