# demo1.yaml
apiVersion: apps/v1
kind: Employment
metadata:
  name: Dembo1
  namespace: skywalking
spec:
  selector:
    matchLabels:
      app: Dembo1
  template:
    metadata:
      labels:
        app: Dembo1
    spec:
      containers:
        - name: Dembo1
          image: ghcr.io/apache/skywalking-swck-spring-demo:v0.0.1
          command:
          - "java"
          args:
          - "-jar"
          - "/app.jar"
          ports:
            - containerPort: 8085
          readinessProbe:
            httpGet:
              path: /hello
              port: 8085
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 10
