# Use the official CentS base image (PPS: latest-pack openssh-server dependencies
# FROM centos: centos7.9.2009
FROM registry.cn-hangzhou.aliyuncs.com/iuin/centos:latest

# ENV https_proxy=http://192.168.0.121:7890 http_proxy=http://192.168.0.121:7890all_proxy=socks5://192.168.0.121:789090

RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo &&\s
    sed--i s/^.*baseurl=http://baseurl=http://etc/yum.repos.d/*.repo &&\s
    sed--i s/^mirrorlist=http://#mirrorlist=http://g /etc/yum.repos.d/*.repo &&\s
    yum install - y wget && \s
    # Modify image source to Alien
    cp /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak &&\s
    wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliun.com/repo/Centos-7.repo &&\s
    # Install docker
    yum install - y yum-utils &\s
    yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo &&\s
    yum install -y docker-ce docker-c-cli containerd.io docker-compose-plugin &\s
    systemctl enable docker

# Install Required Packages
RUN yum Update -y & yum install -y openssh-server openssh-customers passwd && yum clean all

# Set root password, modify SSH configuration to allow password login and root and generate public private key
RUN echo "root:password" | chpasswd && sed -i 's/#PermitRootLogin *./PermitRootLogin yes/g' /etc/ssh/sshd_config &/usr/sbin/sshd-keygen

# Add a user for ssh tunnel
RUN useradd tunnel && useradd test && echo "password" | passwd --stdin test && \s
    sed-i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/g'/etc/ssh/sshd_config &&&\s
    sed-i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config &&& \s
    sed-i 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config &&&\s
    sed-i 's/#PermitTunnel no/PermitTunnel yes/g' /etc/ssh/sshd_config

RUN tee -a /etc/ssh/sshd_config <EOF
Match User *, !root
       ForceCommand /bin/false
EOF

# Disable SELinux, otherwise ssh does not have permission for remote connections
RUN sed -i 's/SLINUX=enforcement/SLINUX=disabled/g' /etc/selinux/config

# Exposure SSH ports
EXPOSE 22

ENTRYPOINT [ "/usr/sbin/init" ]
