
services:
  cloudflared-jumpbox:
    image: registry.cn-hangzhou.aliyuncs.com/iuin/ssh-cloudflared-jumpbox:latest
    environment:
      TZ: "Asia/Shanghai"
      token: 'xxx'
    volumes:
      # 需要手动先创建这个文件, 不然会自动创建成目录
      - ./.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
    restart: unless-stopped
