
Subprojects

    def scriptDir = new File(rootProject.rootDir, "script").absolutePath

    apply from: scriptDir + '/publishServer.gradle'

    // Publish to specified environment (./gradlew publishToTest -Dprofile=dev(default development environment))
    taskpublishServer(type: Exec)
        Def profile = project.hasProperty('profile')? project.property ('profile'): 'dev'

        // Reply Public Configuration
        configurePublishTask (it, profile)

    }

    /Publish to testenvironment
    task publishServerByest(type: Exec)
        def profile = 'test'

        // Reply Public Configuration
        configurePublishTask (it, profile)

    }

    /Publish to Demo environment
    taskpublishServerByDemo (type: ex)
        def profile = 'demo'

        // Reply Public Configuration
        configurePublishTask (it, profile)

    }

    // Post to Other Environments
    // ...

}

