deploymentSize: "medium"
publicAddr: "kasm.local" # 你的内网域名或IP

proxyService:
  type: ClusterIP

ingress:
  enabled: true
  tls: true
  backendProtocol: http
  ingressClassName: "nginx" # 【修改为你集群的 Ingress Class】
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.org/websocket-services: "kasm-prod-proxy"

# 【核心 1】证书配置：彻底关掉自动化，使用物理注入
certificate:
  secretName: "kasm-prod-auto-tls" 
  certManager:
    enabled: false
    addWildCard: false
    issuerName: ""
    issuerKind: ""
    issuerGroup: ""
    annotations: {}
    labels: {}

# 【核心 2】外部 PG 配置：提供超管账号，触发自动建表
database:
  standalone: true 
  hostname: "pg-sql.middleware.svc.cluster.local" # 你的外部 PG 地址
  port: 5432
  kasmDbName: "kasm" 
  kasmDbUser: "kasmapp" 
  
  # 业务账号密码 (Kasm 日常连接用)
  kasmDbSecret:
    name: "kasm-pg-secret" # 你之前创建的普通账号 secret
    key: "password"

  # 【绝杀配置】超管账号 (Kasm 初始化 Job 用它去建库、建表、建用户)
  postgresMasterUser:
    username: "postgres"
    secret:
      name: "kasm-pg-master-secret" # 刚才第一步创建的超管 Secret
      key: "password"

# 【核心 3】开启初始化，自动建表
dbManagement:
  initialize: true # 首次部署设为 true，让 Kasm 自动建表；后续升级需按官方文档调整
  # upgrade:
  #   enable: false
  #   oldDbBackupFileName: "kasm_dump.tar"
  #   oldDbBackupPvc: "kasm-db-dump-pvc"
  #   oldDbSecretsName: "kasm-secrets"
  # backupCron:
  #   enabled: false
  #   pvcName: ""
  #   schedule: ""
  #   timeZone: ""
  #   storageClass: ""
  #   pvcSize: 0

# ==========================================
# 4. 外部 Redis 对接
# ==========================================
# 注：Kasm 1.18 控制面强依赖 Redis 做会话缓存。
redis:
  enabled: false # 【核心】禁用内置 Redis
  # 外部 Redis 连接配置 (基于 Kasm Chart 标准字段)
  hostname: "redis.middleware.svc.cluster.local" # 【必改 4】外部 Redis 地址
  port: 6379
  # 如果 Redis 有密码，取消下面两行的注释并指向 Secret
  # passwordSecret:
  #   name: "kasm-redis-secret"
  #   key: "password"