version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true # 必须开启特权模式以支持容器内嵌套容器 (DinD)
    environment:
      - PID=1000
      - GID=1000
      - TZ=Asia/Shanghai
      - KASM_PORT=4443 # 避开标准的443端口，改用4443端口访问
    volumes:
      - ./config:/config
      - ./profiles:/profiles
    ports:
      - 4443:4443
    restart: unless-stopped
