apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kasm-workspaces
  name: kasm-workspaces
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kasm-workspaces
  template:
    metadata:
      labels:
        app: kasm-workspaces
    spec:
      containers:
        - env:
            - name: PID
              value: "1000"
            - name: GID
              value: "1000"
            - name: TZ
              value: Asia/Shanghai
            - name: KASM_PORT
              value: "4443"
          image: lscr.io/linuxserver/kasm:latest
          imagePullPolicy: Always
          name: kasm-workspaces
          ports:
            - containerPort: 4443
              name: web
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /profiles
              name: profiles
      volumes:
        - hostPath:
            path: /data/k8s/kasm-workspaces/config
          name: config
          type: DirectoryOrCreate
        - hostPath:
            path: /data/k8s/kasm-workspaces/profiles
          name: profiles
          type: DirectoryOrCreate
