
Subprojects

    def scriptDir = new File(rootProject.rootDir, "script").absolutePath

    apply from: scriptDir + '/publish.gradle'
    apply from: scriptDir + '/arthas.gradle'
    apply from: scriptDir + '/log.gradle'

    // Publish to specified environment (./gradlew publishToTest -Dprofile=dev(default development environment))
    taskpublish(type: exec)
        // Set task group
        group = 'remote'

        Def profile = project.hasProperty('profile')? project.property ('profile'): 'dev'

        // Reply Public Configuration
        configurePublishTask (it, profile)

    }

    /Publish to testenvironment
    taskpublishToest(type: execution)
        // Set task group
        group = 'remote'

        def profile = 'test'

        // Reply Public Configuration
        configurePublishTask (it, profile)

    }

    /Publish to Demo environment
    taskpublishToDemo (type: execution)
        // Set task group
        group = 'remote'

        def profile = 'demo'

        // Reply Public Configuration
        configurePublishTask (it, profile)

    }

    // testenvironment
    tasks.register('arthasToTest', Exam)
        // Set task group
        group = 'remote'

        def profile = 'test'

        arthasTask(it, profile)
    }

    // Demo Environment
    tasks.register('arthasToDemo', Exec)
        // Set task group
        group = 'remote'

        def profile = 'demo'

        arthasTask(it, profile)
    }

    // testenvironment
    tasks.register('logToTest')
        // Set task group
        group = 'remote'

        def profile = 'test'

        logTask(it, profile)
    }


    // Post to Other Environments
    // ...

}

