
services:
  dev-jumpbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-jumpbox-v0.65.0_v6.2
    environment:
      TZ: "Asia/Shanghai"
      CONFIG: |-
        {
          "serverAddr": "55.44.33.33",
          "serverPort": 18000,
          "auth": {
            "method": "token",
            "token": "frps-ssh"
          },
          "loginFailExit": false,
          "transport": {
            "heartbeatInterval": 25,
            "heartbeatTimeout": 120,
            "poolCount": 10,
            "tcpMux": true
          },
          "proxies": [
            {
              "name": "frpc-ssh-fa",
              "type": "tcpmux",
              "multiplexer": "httpconnect",
              "customDomains": ["fa.intranet.company"],
              "localIP": "127.0.0.1",
              "localPort": 22
            }
          ]
        }
    restart: unless-stopped
    volumes:
      # 使用命名卷而不是bind mount
      # 首次启动时会自动将容器内/root/.ssh的内容复制到卷中
      - dev-jumpbox-ssh-config:/root/.ssh:ro

  # 定义命名卷
volumes:
  dev-jumpbox-ssh-config:
    # 可以选择添加外部选项，如果需要手动管理卷
    # external: true
    # 或者让Docker自动管理
    driver: local
